env:
  repo: https://github.com/farrukh90/artemis.git
  app_version: 5.0.0
  region: us-central1
  project_id: ${{ secrets.PROJECT_ID }}
  app_name: artemis
  tag_new_version: ${GITHUB_SHA}
  artifact_repositary: test-repositary


name: CDelivery

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3


      - name: Clone a Repo
        run: git clone ${{ env.repo }}

      - name: Build an image
        working-directory: ${{ env.app_name }}
        run: |
          git checkout ${{ env.app_version }}
          docker build -t ${{ env.region }}-docker.pkg.dev/${{ env.project_id }}/${{ env.artifact_repositary }}/${{ env.app_name }}:${{ env.tag_new_version }}    . 
        

      - name: Authenticate to Registry
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT }}'

      - name: Authenticate to Registry
        run: |
          gcloud auth configure-docker ${{ env.region }}-docker.pkg.dev
        

      - name: Push
        run: docker push ${{ env.region }}-docker.pkg.dev/${{ env.project_id }}/${{ env.artifact_repositary }}/${{ env.app_name }}:${{ env.tag_new_version }}
        